[pytest]
pythonpath = .
testpaths = testcases
python_files = test_*.py *Test.py
python_classes = Test*
python_functions = test_*
markers =
    order: Test execution order
    dependency: Test dependencies
