[basic info]
testsiteurl=https://devtr-anonymizationwebtool.sureprep.com/

[pytest]
addopts= --browser-chrome --headed --slowmo=2000

[locators]

#Login
An_username=#username
An_password=#password
An_SignOnBtn=#signOnButton


#Approver Role

An_requesttab= Request
An_DocumentSearch= Document Search
An_engagementId=#engagementId
An_templateName=#templateName
An_pageType=#pageType
An_pageNumber=#pageNumber
An_pageRange=#pageRange
An_startDate=#startDate
An_endDate=#endDate
An_searchBtn= Search Document(s)
An_priorityDrpdown=#priorityHeader
An_selectAllcheckbox=Select All
An_createJobbtn=button[title*="Save"]
An_userRole=div.logo-section > span.logo-text + span
An_requestId=.header-request-id
An_HomeTab= Home

#Redactor Role

An_userRole_Redactor=div.logo-section > span.logo-text + span
An_redactorText=(Redactor)
An_group_id_field=div.filter-input-wrapper input[placeholder="Request ID..."]
An_Assign_btn= Assign
An_Assign_Yes_btn=button.btn.btn-success > span.btn-icon
An_Redaction_Pending_btn= button:has-text(' Redaction Pending ')
An_Enter_FullScreen_btn= [title="Enter Fullscreen"]
An_Exit_FullScreen_btn= [title="Exit Fullscreen"]
An_Zoom_In=button.zoom-btn[title="Zoom In"]
An_Zoom_Out=button.zoom-btn[title="Zoom Out"]
An_redaction_box=.redacted-section .canvas-scroll-container canvas.image-canvas
An_redaction_save_btn= Save
An_Approver_Enter_FullScreen_btn= [title="Enter Fullscreen"]
An_Approver_Exit_FullScreen_btn= [title="Exit Fullscreen"]
An_redaction_Submit= Submit
An_Redactor_HomeTab=a.nav-tab i.fa-home
#Approver Role - Approving request

An_Review_Pending= button:has-text(' Review Pending ')

An_Approve_&_Export_btn= .btn.btn-success

An_Sign_out=a.nav-tab:has(i.fa-sign-out-alt)